name: food_delivery_app
description: "Flutter Delivery App."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  supabase_flutter: ^2.9.1
  font_awesome_flutter: ^10.8.0
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.1
  flutter_polyline_points: ^2.1.0
  permission_handler: ^12.0.0+1
  grouped_list: ^6.0.0
  geocoding: ^4.0.0
  timeline_tile: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/myFoodIcon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/myFoodIcon.png
  android: true
  ios: true

  android_12:
    image: assets/myFoodIcon.png


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
